#!/usr/bin/env python3
"""
간단한 부하 생성기 - FastAPI에 주기적으로 요청을 보냅니다.
"""
import requests
import time
import random
import sys
from datetime import datetime

# FastAPI 앱 URL
FASTAPI_URL = "http://fastapi-app:5001"

def generate_load():
    """지속적으로 부하를 생성합니다."""
    endpoints = [
        ("GET", "/todos"),
        ("GET", "/todos/2025-11-27"),
        ("POST", "/todos"),
        ("GET", "/"),
    ]
    
    print(f"[{datetime.now()}] 부하 생성기 시작: {FASTAPI_URL}")
    
    while True:
        try:
            # 랜덤하게 엔드포인트 선택
            method, endpoint = random.choice(endpoints)
            url = f"{FASTAPI_URL}{endpoint}"
            
            if method == "GET":
                response = requests.get(url, timeout=5)
            elif method == "POST":
                # POST 요청용 데이터
                data = {
                    "id": random.randint(1, 10000),
                    "title": f"Load Test Item {random.randint(1, 1000)}",
                    "description": "Generated by load generator",
                    "completed": False,
                    "date": "2025-11-27"
                }
                response = requests.post(url, json=data, timeout=5)
            
            print(f"[{datetime.now()}] {method} {endpoint} - {response.status_code}")
            
        except requests.exceptions.RequestException as e:
            print(f"[{datetime.now()}] 오류: {e}")
        
        # 1-3초 사이 랜덤 대기 (초당 약 0.5-1 요청)
        time.sleep(random.uniform(1, 3))

if __name__ == "__main__":
    try:
        generate_load()
    except KeyboardInterrupt:
        print("\n부하 생성기 종료")
        sys.exit(0)

